### ISSUE TITLE
Not adding days when intended?

### ISSUE THREAD

**Issue by leion247** [Kraykennn/LC-DynamicDeadline#1]
Maybe I'm doing something wrong, but I've tried installing it both manually and via the launcher. The weird thing is, the scrape limit is the default 200, yet I don't get an additional day after 200 or 400. It's only around 700 I get one extra day that isn't clearly shown. Not clearly shown being that it says I have three days, use a day and still shows three days. After which it continues to count normally down. Once I get about 1000 quota is when I actually see the extra days being 5. Now, I never got 1000 quota before installing this mod, so maybe 5 is just base game, but I feel that if the mod is working as I'd expect it too, I should have either 7 or 8 total days, not 5 by 1000 depending on whether you start counting after 200 or 400. If at 200 giving one day, as in the second quota, then I should 4 in quota 2, and if by 400, then I should have 4 after quota 4. Anyways, I just wanted to get a clear answer on whether this is working as intended or if I'm doing something wrong, because changing the config doesn't appear to do much either, as I'd tried reducing it to 100 to see any difference.

**Comment by Shaosil** [comment]
I opened issue #2 about the config values not working, you can see in the source code that the formula is basically:

`days = Math.Clamp(Math.Ceil(currentQuota / 200), 4, 10)`, which divides the quota by 200, rounds up, and clamps it between 4 and 10 days. Which results in:

- 0-600: 3 days (not sure why the clamp doesn't take affect yet)
- 601-800: 4 days
- 801-1000: 5 days
- ... etc etc

**Comment by leion247** [comment]
Okay, so basically it doesn't count and then add days to the base day value, it just takes into account total days by a new value. Wish that was more clear. Hopefully the config value not changing gets fixed since I have a hard time getting to the 601 quota for an extra day.

**Comment by Kraykennn** [comment]
Hi there, I'm new to GitHub and its capabilities and I forgot there was an issue tab. Currently, the source code for DynamicDeadline on GitHub is inaccurate due to an issue I'm having with updating the master branch. (This is why it seems as though the currently displayed code doesn't utilize any of the newer features such as dailyscrapvalue.) I'm sorry for the lack of concise or clear language when describing the mod, as I usually explain in more detail over in the lethal company modding discord. I'll be updating the readme after I finish the newest update and hopefully eliminate some potential for misunderstanding.
